### PR TITLE
RFC 1: Miscellaneous Cleanup

### PR DESCRIPTION
**Pull request by beaushinkle**
Quick & Simple PR: I noticed some miscellaneous pieces that were individually wrong but weren't big enough to create cards for, so they got lumped together to create a PR.

tagging @michalinacienciala for review

### CODE REVIEW

**Comment by michalinacienciala** [comment]
Looking good. I see that PR is in draft state, so if you're still working on this, I've got one more thing that could be added: listing of governable parameters in the "Bitcoin Sweeping Fee" section - we mention there that the fees are governable, but don't give those params names and don't list them.

**Comment by beaushinkle** [comment]
Definitely down to add that! This PR (and the other ones) are all in draft state so that they don't get merged before the other ones (because they point at an integration branch). Once the earlier PRs get merged I can point this stuff at the main branch otherwise I end up in merge conflict hell!

**Comment by beaushinkle** [comment]
addressed in f9a20cc

**Review by michalinacienciala — DISMISSED** [review]

**Comment by beaushinkle** [comment]
@michalinacienciala now that enough of the original PRs have been merged, i pointed this at main and got the commits resolved. the diff should be identical to when you approved it, so if you're still good feel free to merge

**Review by michalinacienciala — APPROVED** [review]

**Pull request merged**
