### PR TITLE
Remove unnecessary TODO

### PR DESCRIPTION
**Pull request by tomaszslabon**
We decided to remove the TODOs because only a selected set of maintainers will be reimbursed for calling this function, and those maintainers will be working on round-robin duty. There is a low risk that someone will try to frontrun the call. At the same time, doing this change would complicate the code so we think it is not worth it.

### CODE REVIEW

**Comment by pdyraga** [comment]
We need to describe in the PR description and in the commit description *why* it's been decided this way.

And the reason is that only a selected set of maintainers will be reimbursed for calling this function, and those maintainers will be working on round-robin duty. There is a low risk that someone will try to frontrun the call. At the same time, doing this change would complicate the code so we think it is not worth it.

**Comment by tomaszslabon** [comment]
> We need to describe in the PR description and in the commit description _why_ it's been decided this way.
> 
> And the reason is that only a selected set of maintainers will be reimbursed for calling this function, and those maintainers will be working on round-robin duty. There is a low risk that someone will try to frontrun the call. At the same time, doing this change would complicate the code so we think it is not worth it.

I changed the description.

**Comment by pdyraga** [comment]
Let's also amend the commit to explain it in the details section.

**Comment by tomaszslabon** [comment]
> Let's also amend the commit message to explain it in the details section.

Done.

**Review by pdyraga — APPROVED** [review]

**Pull request merged**
